// Creating Array & array is type of Obj
// an array is a list of value, we can access uisng Index value and indexing always starts at 0
// let cars = ['Benzs' , "Volvo", "Audi", "BMW"];
// console.log(typeof (cars));

// -----------------------------------------------------------------//

// Craeting Array with const 
// We Can't change the refence ,but We can edit the elements of the Array


const cars = ['Benzs' , "Volvo", "Audi", "BMW"];
let Myfav= cars.slice(-4);
console.log(Myfav)

// I should complete this by tomorrow
/*
push(), pop(), shift(), unshift()

slice(), splice()

forEach(), map()

filter(), find(), includes()

sort(), reverse()
*/