// printing statement
// console.log("Hello world");

// -----------------------------------------------------------------//
//declare variables
// let,var,const
// let a =10;
// const b = 20 ; 
// var c = 30;

// -----------------------------------------------------------------//
// d=a+b+c;
// console.log(d);

// -----------------------------------------------------------------//
//let KeyWord
// {
//     let a = 10;
// }
//a can't be used in outer of the scope
//and we can't redeclare the a variable 

//var KeyWord
// {
//     var a = 20;
// }
// console.log(a)
// a can we use outer of the scope
// and we can redeclare the a variable

//const Keyword
// {
//     a= 10;
// }
//a we can't be used in outer of the scope
// and we can't redeclare the a variable
// -----------------------------------------------------------------//

//Data Types
// a =123;
// b = "Hello";
// c = true;
// d = undefined;
// e = null;
// f= Symbol(123);

// console.log(typeof(f));
// -----------------------------------------------------------------//


//Just normal string
// 
// let text = 'You can call me "siva" ';
// 
// console.log(text);
// -----------------------------------------------------------------//

//String interpolation

// let text = "Siva"

// console.log(`Hey there ,This me ${text}`);
// -----------------------------------------------------------------//



