// For assing the vaule 
// let = 10;
// we can use  '='
// -----------------------------------------------------------------//
//Arithmetic Operators add,sub,multi,divion,modulus,exponenation

// let a = 10;
// let b = 20;

// a+b
// a-b
// a/b
// a%b
// a**b
// a*b
// -----------------------------------------------------------------//

//Assingment Operators Just we can use  "=" iseqauls to sysmbol
// let a = 10;
// let b =20;

// a=b;
// a+=b;
// a-=b;
// a/=b
// a%=b

// console.log(a-=b)
// -----------------------------------------------------------------//

//Spread operator to spread the into char

// let a ="Hello World"
// let hello = [...a]

// console.log(hello)


